### ISSUE TITLE
Soucis css

### ISSUE THREAD

**Issue by neomanu16** [weather34/Weather34-MB-SMART-Console#1]
HI Brian I think there is a concern with css that on chrome in fact not on IE
![FireShot Capture 096 - Météo_Vars - www meteo16-vars com](https://user-images.githubusercontent.com/47469020/77096266-63d24600-6a0f-11ea-8852-08852de2182b.png)

**Comment by weather34** [comment]
resolved earlier please update css files...Brian

![Screenshot at Mar 19 20-48-16](https://user-images.githubusercontent.com/20555738/77098188-00521380-6a23-11ea-9289-6e0189d35e15.png)
