### ISSUE TITLE
Missing translations for DK

### ISSUE THREAD

**Issue by briis** [weather34/Weather34-MB-SMART-Console#2]
Hi Brian,
In the latest update (April 11th, 2020) the Danish language file has a few missing translations. I have fixed this and attached the file here.

[lang.dk.php.zip](https://github.com/weather34/Weather34-MB-SMART-Console/files/4479296/lang.dk.php.zip)

**Comment by weather34** [comment]
thank you i just updated the repo .. unfortunately cant update download site very poor internet here almost like telephone 1990 dial up since “stay at home” policy..
