### ISSUE TITLE
Updated DK translation for April 23rd release

### ISSUE THREAD

**Issue by briis** [weather34/Weather34-MB-SMART-Console#3]
Hi Brian,
Attached an updated language file for the latest release.
[lang.dk.php.zip](https://github.com/weather34/Weather34-MB-SMART-Console/files/4527224/lang.dk.php.zip)

**Comment by weather34** [comment]
hello Bjarne 

you have privileges granted to upload direct to the repo .you were granted those based on previous contributions. if you are unsure let me know i will update the file .just thought i would mention if your not aware . however if unsure always download a master before making uploads.brian

**Comment by briis** [comment]
Hi Brian,
Yes I knew I had the rights, I just wasn’t sure how you wanted this to happen. Should I make a PR and then you merge, or should I upload directly to the master?

De bedste hilsner,

Bjarne Riis
Toftebuen 146
4000 Roskilde
Mobil: 2619 1701
E-Mail: bjarne@briis.com<mailto:bjarne@briis.com>

**Comment by weather34** [comment]
if you have 100% tested it and happy with the translations .then upload direct into the languages folder. i can always check as i get a notification and always keep a master on desktop. testing often involves checking alignments particularly if the wording is lengthened.

**Comment by weather34** [comment]
sometimes its worth waiting a day or two as scenarios vary from day to day, hour to hour

**Comment by weather34** [comment]
I just uploaded dk lang file ..

**Comment by briis** [comment]
OK. Thanks for clarifying Brian.
And btw, thanks for the great template – Love it.

De bedste hilsner,

Bjarne Riis
Toftebuen 146
4000 Roskilde
Mobil: 2619 1701
E-Mail: bjarne@briis.com<mailto:bjarne@briis.com>
